<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elDescription</name>
   <tag></tag>
   <elementGuidId>979f419b-a3aa-4a76-8bf4-6fda5b71ad42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[@id = 'tinymce']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tinymce&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tinymce</value>
      <webElementGuid>c4c1d1d7-02bf-4b27-b753-4c63be874a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>de1c1703-9093-44a3-bc46-6b6c4eaafa15</webElementGuid>
   </webElementProperties>
</WebElementEntity>
