<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elSummary</name>
   <tag></tag>
   <elementGuidId>52540b51-6de1-4efc-9de2-cee293c27952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;summary&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;summary&quot;]</value>
      <webElementGuid>9018137c-d702-45f5-bfef-75368577cb80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
