<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>elIssueSummary</name>
   <tag></tag>
   <elementGuidId>783cc90b-2d80-4765-b074-6b06a60ce0b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='issue-content']//h1[@id='summary-val']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;summary-val&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='issue-content']//h1[@id='summary-val']</value>
      <webElementGuid>ef44e684-b30f-4ec5-85c7-10312f81bc99</webElementGuid>
   </webElementProperties>
</WebElementEntity>
